language: objective-c
before_install:
  - chmod a+x travis/before_script.sh
  - chmod a+x travis/script.sh
install:
  - pod install --no-integrate
before_script: travis/before_script.sh
script: travis/script.sh
